// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PegsBase.Data;

#nullable disable

namespace PegsBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250330125151_AddedCalculatedDataToRawSurveyData")]
    partial class AddedCalculatedDataToRawSurveyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PegsBase.Models.PegRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FromPeg")
                        .HasColumnType("text");

                    b.Property<decimal?>("GradeElevation")
                        .HasColumnType("numeric");

                    b.Property<bool>("HasPegCalc")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PegFailed")
                        .HasColumnType("boolean");

                    b.Property<string>("PegName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PointType")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SurveyDate")
                        .HasColumnType("date");

                    b.Property<string>("Surveyor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("XCoord")
                        .HasColumnType("numeric");

                    b.Property<decimal>("YCoord")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ZCoord")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PegRegister");
                });

            modelBuilder.Entity("PegsBase.Models.RawSurveyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BackBearingReturn")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BackCheckHorizontalDifference")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BackCheckHorizontalDistance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BackCheckPegElevations")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BackCheckVerticalError")
                        .HasColumnType("numeric");

                    b.Property<string>("BackSightPeg")
                        .HasColumnType("text");

                    b.Property<decimal>("BacksightPegX")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BacksightPegY")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BacksightPegZ")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeltaX")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeltaY")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeltaZ")
                        .HasColumnType("numeric");

                    b.Property<string>("ForeSightPeg")
                        .HasColumnType("text");

                    b.Property<decimal>("ForwardBearing")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ForwardBearingReturn")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleDirectArc1Backsight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleDirectArc1Foresight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleDirectArc2Backsight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleDirectArc2Foresight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleDirectReducedArc1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleDirectReducedArc2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleMeanArc1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleMeanArc2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleMeanFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleMeanFinalReturn")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleTransitArc1Backsight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleTransitArc1Foresight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleTransitArc2Backsight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleTransitArc2Foresight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleTransitReducedArc1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HAngleTransitReducedArc2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HorizontalDistanceBacksight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HorizontalDistanceForesight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InstrumentHeight")
                        .HasColumnType("numeric");

                    b.Property<string>("Locality")
                        .HasColumnType("text");

                    b.Property<decimal>("NewPegX")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NewPegY")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NewPegZ")
                        .HasColumnType("numeric");

                    b.Property<bool>("PegFailed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SlopeDistanceBacksight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SlopeDistanceForesight")
                        .HasColumnType("numeric");

                    b.Property<string>("StationPeg")
                        .HasColumnType("text");

                    b.Property<decimal>("StationPegX")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StationPegY")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StationPegZ")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("SurveyDate")
                        .HasColumnType("date");

                    b.Property<string>("Surveyor")
                        .HasColumnType("text");

                    b.Property<decimal>("TargetHeightBacksight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TargetHeightForesight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleBacksightMeanArc1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleBacksightMeanArc2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleBacksightMeanFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleDirectArc1Backsight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleDirectArc1Foresight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleDirectArc2Backsight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleDirectArc2Foresight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleForesightMeanArc1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleForesightMeanArc2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleForesightMeanFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleTransitArc1Backsight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleTransitArc1Foresight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleTransitArc2Backsight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAngleTransitArc2Foresight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VerticalDifferenceBacksight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VerticalDifferenceForesight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("RawSurveyData");
                });
#pragma warning restore 612, 618
        }
    }
}
